import { useEffect } from 'react'
import { useAppDispatch } from '../../store'
import { isUserAuthenticated } from '../../store/async/userAsync'
import { useSelector } from 'react-redux'
import { RootState } from '../../store/rootRoducer'