"use client";
import { useEffect } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from './src/components/mainComponents/Providers';
import { ToastContainer } from "react-toastify";
import { isUserAuthenticated } from "./src/store/async/userAsync";
import { useAppDispatch } from "./src/store";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create Chat app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const dispatch = useAppDispatch();
  useEffect(() => {
    //  Dispatch the authentication check when the component mounts
    dispatch(isUserAuthenticated());
  }, [dispatch]);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {children}
        </Providers>
        <ToastContainer />
      </body>
    </html>
  );
}
